Add bluetooth readout
flok/pydualsense pull request #42
Opened 2023-02-02 21:37 UTC by triveria

Hi,
this MR implements a simple (but not so elegant) method to read out the controller via bluetooth.
I haven't found a more elegant method yet.
It works on Linux. I haven't tested it on Windows.

2023-02-04 10:46 UTC, flok requested changes

2023-02-04 10:46 UTC, flok commented on examples/read_all_input_channels.py
> +while True:
could you add some option to gracefully close the curses display and stop the example? maybe by pressing q ?

2023-02-04 10:46 UTC, flok commented on examples/read_all_input_channels.py
> +    # time.sleep(0.1)
not necessary

2023-02-04 10:47 UTC, flok commented
Thanks for the PR! Added some little comments before merging

2023-02-04 13:45 UTC, triveria commented
Thanks for your suggestions. I've incorporated them now

2023-02-05 15:30 UTC, flok approved these changes

2023-02-05 15:30 UTC, merged